### ISSUE TITLE
Разработать функционал регистрации пользователя

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#1]
**Конечный результат:**
У пользователя должна быть возможность зарегистрироваться в системе, чтобы он мог использовать функциональность системы.

**План решения:**
Создать локальный проект с названием Starkit по шаблону MVC с гит репозиторием на устройстве. После чего подготовить проект к началу работы удалив все лишнее. Добавить файл gitignore. Выполнить инициализирующий коммит. Связать локальный репозиторий с удаленным и запушить первичные файлы. Связать проект с базой данных PostGres. Далее сделать подключение функционала аутентификации пользователя с помощью Identity
В рамках данной задачи, от вас потребуется реализовать следующий функционал:
●	Регистрация пользователей (Пользователь должен указывать следующие данные при регистрации, см эскиз)
![photo_2020-07-25_10-16-52](https://user-images.githubusercontent.com/18418768/88485075-16557f00-cf95-11ea-9752-d72055d82961.jpg)
●	Валидацию введенных данных при регистрации по следующим правилам:
○	Нельзя зарегистрировать пользователя с уже существующим email или username
○	Нельзя регистрировать пользователя возрастом моложе 18 лет.
○	Пароль должен содержать в себе 1 букву верхнего регистра, 1 букву нижнего регистра, а также минимум 1 цифру, длина пароля не менее 6 символов.
○	Все сообщения валидации должны выводиться на русском языке.
●	Получение на электронную почту уведомления о регистрации:
○	email должен содержать все регистрационные данные и ссылку на личный кабинет для быстрого перехода

**Критерии приема:**
У пользователя должна быть возможность пройти регистрацию и войти в личный кабинет

**Планируемое время:**
2 дня

**Comment by seyderaly98** [comment]
Затраченная время на выполнение задачи около 18 часов
