### ISSUE TITLE
Функционал об утверждении правил регистрации пользователей на сайте

### ISSUE THREAD

**Issue by seyderaly98** [ESDP-Csharp-2-3-Team1/starkit#11]
**Конечный результат:**
Чтобы зарегистрировать нового пользователя необходимо принять правила сервиса. Кнопка регистрации не должно срабатывать если пользователь не согласен. 

**План решения:**
В сущность пользователя нужно добавить поле подтверждение правил с типом bool. Функционал можно реализовать с двумя способами:
1) http://prntscr.com/ttazuh
2) http://prntscr.com/ttb0n4

В рамках данной задачи, от вас потребуется реализовать следующий функционал:
●   Функционал об утверждении правил регистрации пользователей на сайте (правила сервиса).
●  Ссылка на правила сервиса ( модальное окно или открыть ссылку в новой вкладке).

**Критерии приема:**

**Планируемое время:**
2 часа

**Comment by samzhex** [comment]
Затраченное время 2 часа
