### ISSUE TITLE
Функционал ввода капчи после 3 попыток авторизации

### ISSUE THREAD

**Issue by seyderaly98** [ESDP-Csharp-2-3-Team1/starkit#13]
**Конечный результат:**

![Screenshot](https://user-images.githubusercontent.com/46619392/89208260-d2d6c280-d5dd-11ea-8b30-5a1ab6af11b7.png)

**План решения:**
Есть несколько вариантов, таких как Google ReCaptcha и Google ReCaptcha. captcha.com оба они могут быть интегрированы в ASP.NET. Также можно  сгенерировать код captcha самостоятельно, этот пост покажет вам, как генерировать и использовать код captcha https://edi.wang/post/2018/10/13/generate-captcha-code-aspnet-core.

В рамках данной задачи, от вас потребуется реализовать следующий функционал:
●	Добавить функционал ввода капчи, после 3 попыток неудачной авторизации.
○	

**Критерии приема:**

**Планируемое время:**
4 часа

**Comment by samzhex** [comment]
Затраченное время 2,5 часа

**Comment by Samat090598** [comment]
Капча появляется после 4 попыток, после появление капчи без его проверки можно войти.
