### ISSUE TITLE
Управление списком подкатегорий

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#16]
Конечный результат:
Есть у нас список подкатегорий который относится к этому ресторатору. Мы можем просмотреть этот список и управлять им(удалять, редактировать)

План решения:
Нужно сделать страницу со списком подкатегорий. Добавить экшены для удаление и редактирование подкатегорий. И добавить соответствующие ссылки для удаление и редактирование подкатегорий.

Критерии приёмки:
Пользователь заходит на страницу со списком подкатегорий и может удалить подкатегорию или редактировать. Когда пользователь изменяет название подкатегорий нельзя допускать если это название соответствует существующей подкатегорий который относится к этому ресторатору.

Планируемое время работы:
5 часов

**Comment by 7119967** [comment]
потраченое время 1:45 мин.
