### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by seyderaly98** [ESDP-Csharp-2-3-Team1/starkit#17]
**Конечный результат:**
После переустановки пароля можно заходить на сайт под тем же электронным адресом и новым паролем.

**План решения:**
В рамках данной задачи, от вас потребуется реализовать функционал сброс пароля с помощью электронного адреса.

Рекомендую такой вариант:
1. Пользователь запрашивает восстановление пароля  https://prnt.sc/ttcja0
2. Шлём ему на почту письмо со специальной ссылкой, содержащей токен
3. Пользователь переходит по ссылке из письма
4. Сверяем токен, после чего авторизуем его и даем задать новый пароль
5. Сохраняем хеш пароля в БД
Механизм сброса пароля в ASP.NET Identity https://metanit.com/sharp/mvc5/12.10.php

**Критерии приема::**
— Токен — достаточно длинная строка из случайных символов
— У токена должен быть срок действия, например 1 час. Это обезопасит систему от перебора токенов

**Планируемое время:**
1 день

**Comment by samzhex** [comment]
Затраченное время 6 часов
