### ISSUE TITLE
Подсвечивание активных ссылок в меню навигации (2 часа)

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#19]
**Конечный результат:**
Активная ссылка в меню подсвечивается и информирует пользователя о нахождении на текущей странице.

**План решения:**
В рамках данной задачи необходимо активной ссылке присвоить класс 'active'.

**Критерии приёмки:**
При переходе пользователя на страницу подсвечивается активная ссылка в навигации приложения

**Планируемое время работы:**
2 часа

**Comment by seyderaly98** [comment]
Затраченное время 2 часа.
