### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#2]
**Конечный результат:**
У пользователя должна быть возможность войти в систему (логин), а также выход из системы (логаут)

**План решения:**
В рамках данной задачи, от вас потребуется реализовать следующий функционал:
●	Вход в приложение (Для входа будут использоваться следующие данные):
○	Username / Email
○	Пароль
●	Выход из приложения.
●	В форме входа и регистрации с помощью JS реализовать возможность просмотра пароля по клику на иконку глаз в поле ввода пароля.

**Критерии приема:**
У пользователя должна быть возможность залогиниться и открыть главную страницу

**Планируемое время:**
1 день

**Comment by seyderaly98** [comment]
Затраченная время на выполнение задачи около 3 часов
