### ISSUE TITLE
Добавить вложенные ссылки в меню навигации (2 часа)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#22]
**Конечный результат:**
При клике на ссылку в меню навигации в личном кабинете появляются вложенные ссылки

План решения:
Можно реализовать на основе https://getbootstrap.com/docs/4.0/components/navs/#using-dropdowns

![Личный кабинет Ресторатора](https://user-images.githubusercontent.com/44899374/90004984-5c5e5280-dcb8-11ea-868f-6b540140eaa7.png)

**Критерии приёмки:**
При клике на ссылку в меню навигации в личном кабинете появляются вложенные ссылки, основные ссылки находящиеся после открытой смещаются ниже на высоту открытой вкладки с вложенными ссылками.

**Планируемое время работы:**
2 часа

**Comment by seyderaly98** [comment]
Затраченное время 3 часов. 
Осталось добавить анимацию, в данном этапе предлагаю пропустить. 
Для реализации  функционала данный метод не подошло https://getbootstrap.com/docs/4.0/components/navs/#using-dropdowns применил js.
