### ISSUE TITLE
Заменить капчу при авторизаций (3 часа)

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#24]
**Конечный результат:**
После 3-х неудачных попыток входа, появляется буквенно-символьная капча.

**План решения:**
Удалить функциональность появления recaptcha. И добавить буквенно-символьную капчу.  Как вариант можно использовать https://edi.wang/post/2018/10/13/generate-captcha-code-aspnet-core

**Критерии приёмки:**
После 3-х неудачных попыток входа пользователя должна появляться буквенно-символьная капча. Не допускается вход пользователя пока не проходит проверку на капчу

**Планируемое время:**
3 часа

**Comment by samzhex** [comment]
Затрачено 3 часа
