### ISSUE TITLE
Регистрация ресторана (6 часов)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#29]
Конечный результат:
Пользователь может зарегистрировать свой ресторан для полноценного использования приложения.

План решения:
Добавить сущность Ресторан со следующими свойствами:

- название
- номер телефона
- контактное лицо
- адрес
- информация о ресторане
- домен
- лого
- график работы ресторана
- количество мест
- доступен для бронирования
- график и условия приема заказов и доставки

При регистрации запросить следующие поля:
![Ресторан форма](https://user-images.githubusercontent.com/44899374/90018668-195ba980-dccf-11ea-9e41-d3be7f670c0e.png)

Критерии приёмки:
Пользователь вводит данные ресторана. При наличии собственного домена, появляются поля "Домен" и "Регистратор". При клике на кнопку "Сохранить" переход на личный кабинет Ресторатора с информацией указанной при регистрации.

Планируемое время:
6 часов

**Comment by seyderaly98** [comment]
Затраченное время 6 часов.
