### ISSUE TITLE
Доработка функционала дополнения данных пользователя (3 часа)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#31]
**Конечный результат:**
После регистраций пользователь должен иметь возможность вводить данные не указанные при регистрации.

**План решения:**
В личном кабинете доработать сохранение введенной информации в полях незаполненных при регистрации.

**Критерии приёмки:**
После того как пользователь регистрируется и переходит в личный кабинет, он может ввести и сохранить дополнительную информацию.

**Планируемое время:**
3 часа

**Comment by seyderaly98** [comment]
Пришлось переделать функционал заново. 
Затраченное время 3 часа.
