### ISSUE TITLE
Добавление акций (6 часов)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#35]
Конечный результат:
Дать возможность сотруднику ресторана добавлять акции 1+1=3 и 1+1=1

План решения: 
![Добавить акцию](https://user-images.githubusercontent.com/44899374/90371312-9a7cbd00-e090-11ea-9a46-1bad851e7ea8.png)

Критерии приёмки:
По клику на вкладку "Добавить акцию" пользователь переходит на страницу добавления акции. Для выбора типа акции предусмотрен выпадающий список. При выборе срока действия меняются поля ввод даты/ ввод времени. 
После добавления переход на список блюд

Планируемое время:
6 часов

**Comment by Samat090598** [comment]
Потратил 5,5 часов. Самое сложно было определить логику добавления блюд в акцию. Пробовал несколько вариантов и решил сделать добавление блюд в акцию на странице добавление акций. И теперь я думаю, нет необходимости #36 задачи. По моей логике когда мы добавляем в акцию мы должны указать два каких-то блюда(могут быть разными) и подарочное блюдо. Например, если покупатель берет боксмастер и фри, то пепси в подарок и т.д. Я не видел возможности такого добавление на странице блюд.
