### ISSUE TITLE
Реализация роли Менеджер по контенту (8 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#39]
**Конечный результат:**
Реализовать в приложении роль Менеджер по контенту.

**План решения:**
Согласно приведенной ниже матрицы ролей реализовать возможные действия роли **Менеджер по контенту** относительно имеющегося в системе функционала.
| **Основной функционал**                    | **Подфункционал**                                   | **Супер Админ**                                                                                                 | **Регистрант**                                                                                                  | **Менеджер по контенту**                        | **Администратор заведения**                                                              |
|--------------------------------------------|-----------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|-------------------------------------------------|------------------------------------------------------------------------------------------|
| **Регистрация пользователя в приложении:** | **-**                                               | заполнение данных для регистрации в приложение; для ИП                                                          | заполнение данных для регистрации в приложение; для ИП                                                          | \-                                              | \-                                                                                       |
|                                            |                                                     | заполнение регистрационных данных для последующей регистрации домена; для ИП                                    | заполнение регистрационных данных для последующей регистрации домена; для ИП                                    | \-                                              | \-                                                                                       |
|                                            |                                                     | ввод капчи при регистрации для предотвращения фрода;                                                            | ввод капчи при регистрации для предотвращения фрода;                                                            | \-                                              | \-                                                                                       |
|                                            |                                                     | подтверждение email;                                                                                            | подтверждение email;                                                                                            | \-                                              | \-                                                                                       |
|                                            |                                                     | подтверждение согласия с офертой.                                                                               | подтверждение согласия с офертой.                                                                               | \-                                              | \-                                                                                       |
| **Авторизация:**                           | **-**                                               | ввод логина и пароля;                                                                                           | ввод логина и пароля;                                                                                           | ввод логина и пароля;                           | ввод логина и пароля;                                                                    |
|                                            |                                                     | валидация при неверном вводе логина или пароля;                                                                 | валидация при неверном вводе логина или пароля;                                                                 | валидация при неверном вводе логина или пароля; | валидация при неверном вводе логина или пароля;                                          |
|                                            |                                                     | капча после 3х неуспешных попыток                                                                               | капча после 3х неуспешных попыток                                                                               | капча после 3х неуспешных попыток               | капча после 3х неуспешных попыток                                                        |
| **Регистрация ресторана:**                 | **-**                                               | установка логотипа компании регистранта;                                                                        | установка логотипа компании регистранта;                                                                        | \-                                              | \-                                                                                       |
|                                            |                                                     | установка наименования компании регистранта (торговый бренд);                                                   | установка наименования компании регистранта (торговый бренд);                                                   | \-                                              | \-                                                                                       |
|                                            |                                                     | краткое описание предприятия регистранта, для отображения в разделе сайта “О компании”;                         | краткое описание предприятия регистранта, для отображения в разделе сайта “О компании”;                         | \-                                              | \-                                                                                       |
|                                            |                                                     | установка имеющегося доменного имени;                                                                           | установка имеющегося доменного имени;                                                                           | \-                                              | \-                                                                                       |
|                                            |                                                     | выбор и проверка доменного имени (интеграция с хостером в случае если нет зарегистрированного доменного имени); | выбор и проверка доменного имени (интеграция с хостером в случае если нет зарегистрированного доменного имени); | \-                                              | \-                                                                                       |
|                                            |                                                     | настройка количества мест;                                                                                      | настройка количества мест;                                                                                      | \-                                              | настройка количества мест;                                                               |
|                                            |                                                     | возможность бронирования посадочных мест в ресторане;                                                           | возможность бронирования посадочных мест в ресторане;                                                           | \-                                              | возможность бронирования посадочных мест в ресторане;                                    |
|                                            |                                                     | график работы заведения регистранта;                                                                            | график работы заведения регистранта;                                                                            | \-                                              | график работы заведения регистранта;                                                     |
|                                            |                                                     | график и условия приема и доставки заказов.                                                                     | график и условия приема и доставки заказов.                                                                     | \-                                              | график и условия приема и доставки заказов.                                              |
| **Личный кабинет:**                        | **управление меню;**                                | предоставить возможность создание нескольких меню ( например диетическое, детское и тд.)                        | предоставить возможность создание нескольких меню ( например диетическое, детское и тд.)                        | просмотр списка меню                            | предоставить возможность создание нескольких меню ( например диетическое, детское и тд.) |
|                                            |                                                     | удаление и редактирования списка меню.                                                                          | удаление и редактирования списка меню.                                                                          | \-                                              | удаление и редактирования списка меню.                                                   |
|                                            | **управление посадочными местами;**                 | настройка количества мест;                                                                                      | настройка количества мест;                                                                                      | \-                                              | настройка количества мест;                                                               |
|                                            | **управление категориями блюд**                     | просмотр категорий                                                                                              | просмотр категорий                                                                                              | создание и редактирование категорий             | просмотр категорий                                                                       |
|                                            | **управление подкатегориями блюд**                  | просмотр подкатегорий                                                                                           | просмотр подкатегорий                                                                                           | создание и редактирование подкатегорий          | просмотр подкатегорий                                                                    |
|                                            | **управление блюдами;**                             | просмотр блюд                                                                                                   | просмотр блюд                                                                                                   | создание и редактирование блюд                  | просмотр блюд                                                                            |
|                                            | **управление бронированием посадочных мест;**       | возможность бронирования посадочных мест в ресторане;                                                           | возможность бронирования посадочных мест в ресторане;                                                           | \-                                              | возможность бронирования посадочных мест в ресторане;                                    |
|                                            | **управление акциями;**                             | добавление акций                                                                                                | добавление акций                                                                                                | \-                                              | добавление акций                                                                         |
|                                            |                                                     | удаление акций                                                                                                  | удаление акций                                                                                                  | \-                                              | удаление акций                                                                           |
|                                            |                                                     | временное отключение акций                                                                                      | временное отключение акций                                                                                      | \-                                              | временное отключение акций                                                               |
|                                            |                                                     | задать время работы акций ( расписание)                                                                         | задать время работы акций ( расписание)                                                                         | \-                                              | задать время работы акций ( расписание)                                                  |
|                                            | **управление личными настройками кабинета;**        | Редактирование данных профиля ресторана                                                                         | Редактирование данных профиля ресторана                                                                         | \-                                              | Редактирование данных профиля ресторана                                                  |
|                                            | **управление веб страницей заведения**              | управление контентом;                                                                                           | управление контентом;                                                                                           | управление контентом;                           | \-                                                                                       |
|                                            |                                                     | управление скинами веб страницы;                                                                                | управление скинами веб страницы;                                                                                | управление скинами веб страницы;                | \-                                                                                       |
|                                            |                                                     | Отображение изменений на сайте визитке                                                                          | Отображение изменений на сайте визитке                                                                          | Отображение изменений на сайте визитке          | \-                                                                                       |
|                                            | **управление заказами (продажами)**                 | принятие заказа в обработку                                                                                     | принятие заказа в обработку                                                                                     | \-                                              | принятие заказа в обработку                                                              |
|                                            |                                                     | назначение заказа на исполнение                                                                                 | назначение заказа на исполнение                                                                                 | \-                                              | назначение заказа на исполнение                                                          |
|                                            |                                                     | отправка заказа на доставку                                                                                     | отправка заказа на доставку                                                                                     | \-                                              | отправка заказа на доставку                                                              |
|                                            |                                                     | просмотр данных заказа (содержание заказа, адрес доставки, дата и время заказа)                                 | просмотр данных заказа (содержание заказа, адрес доставки, дата и время заказа)                                 | \-                                              | просмотр данных заказа (содержание заказа, адрес доставки, дата и время заказа)          |
|                                            | **управление пользователями для работы в кабинете** | создание, редактирование и блокировка учетных записей                                                           | создание, редактирование и блокировка учетных записей                                                           | \-                                              | создание, редактирование и блокировка учетных записей                                    |
|                                            |                                                     | назначение ролей доступов                                                                                       | назначение ролей доступов                                                                                       | \-                                              | назначение ролей доступов                                                                |
|                                            | **Статистика продаж**                               | Просмотр наилучших продаж (часто заказываемые блюда)                                                            | Просмотр наилучших продаж (часто заказываемые блюда)                                                            | \-                                              | Просмотр наилучших продаж (часто заказываемые блюда)                                     |
|                                            |                                                     | Выборка всех продаж в разрезе день \\ неделя \\ месяц.                                                          | Выборка всех продаж в разрезе день \\ неделя \\ месяц.                                                          | \-                                              | Выборка всех продаж в разрезе день \\ неделя \\ месяц.                                   |
| **интеграция с Glovo**                     | \-                                                  | \-                                                                                                              | \-                                                                                                              | \-                                              | \-                                                                                       |

**Критерии приемки:**
Менеджер по контенту управляет информацией внутри сайта  - ( информативного характера (исключая меню)

**Планируемое время:**
8 часов

**Comment by seyderaly98** [comment]
Функционал управление веб страницей заведения еще не реализован, так что не смог предоставить доступ Менеджеру по контенту

**Comment by seyderaly98** [comment]
Затраченное время 1 час

**Comment by seyderaly98** [comment]
Затраченное время  3 часа
