### ISSUE TITLE
Добавить модальное окно с детальной страницей для списка блюд (6 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#41]
### Конечный результат:
Реализовать раздел навигационного меню для отображения списка имеющихся меню блюд. Для просмотра записи из списка меню должно отображаться модальное окно с детализацией.

### План решения:
В рамках данной задачи необходимо реализовать список меню и с помощью ajax вызов выбранной из списка записи от сервера с последующим отображением ее содержимого в модальном окне. 

### Критерии приёмки:
Пользователь переходит на страницу со списком меню, и там пользователю должна быть предоставлена возможность просмотра записи меню в модальном окне.

### Планируемое время:
6 часов

**Comment by Samat090598** [comment]
Закончил за 3 часа. Проблем не возникло
