### ISSUE TITLE
Редактирование и удаление акций (6 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#42]
### Конечный результат:
Реализовать раздел навигационного меню для отображения списка акций. Для просмотра записи из списка акций по клику на названии акции должно отображаться модальное окно с детализацией.

### План решения:
В рамках данной задачи вам необходимо реализовать список акций и с помощью ajax вызов выбранной из списка записи от сервера с последующим отображением ее содержимого в модальном окне. Также необходимо реализовать действия редактирования и удаления записи.
Для разработки страницы с отображением акции используйте мокапы дизайна с компонентами управления представленных по следующим ссылкам: 
* <a href="https://drive.google.com/file/d/1qVSdQWGvrlRcoozYkyISQliQa7Ws36q5/view?usp=sharing">Добавление акции</a>
* <a href="https://drive.google.com/file/d/1JLuK2Kvj5HXN5jOe4MQFVXJDtBaf6LzN/view?usp=sharing">Добавить акцию</a>

### Критерии приёмки:
Пользователь переходит на страницу со списком акций, и там пользователю должна быть предоставлена возможность просмотра записи акции в модальном окне. В списке акций пользователю должны быть доступны кнопки Удаления и Редактирования записи.

### Планируемое время:
6 часов

**Comment by Samat090598** [comment]
Закончил за 3 часа 45 минут, Проблем не возникло
