### ISSUE TITLE
Реализовать шаблон для сайта-визитки (8 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#43]
### Конечный результат:
Требуется реализовать шаблон для сайта-визитки, чтобы в дальнейшем оснастить его необходимым функеционалом для работы клиентов по формированию заказов.

### План решения:
В рамках данной задачи для реализации шаблона сайта-визитки вам необходимо:
* в проект добавить новый мастер-layout
* в представления добавить папку Site и внутри создать страницу Index, таким образом чтобы обращение к главной странице сайта в браузере было по похожей ссылке http://localhost:5000/Site/Index
* сверстать главную страницу с отображением сайта-визитки в соответствии с представленным <a href="https://drive.google.com/file/d/19wbxe_Fy9y5KDSCJfhD3b6r9dqCytGff/view?usp=sharing">мокапом дизайна</a>
На странице должно быть по крайней мере Шапка, главное меню, раздел с описанием, раздел для отображениям Меню, раздел для отображения категорий и десертов, а также футер.
Дальнейшее наполнение контентом и добавление функционала сайта-визитки будет реализовано отдельными тикетами.

### Мотивация: 
На данный момент у клиентов нет возможности открывать сайт-визитку, а ресторатор не может управлять контентом сайта-визитки.

### Критерии приемки:
Набираем в адресной строке ссылку http://localhost:5000/Site/Index, и браузер отображает сайт похожий на мокап дизайна.

### Планируемое время:
8 часов

**Comment by Samat090598** [comment]
Закончил работу за 6 часов 10 минут. Сделал шаблон сайт визитки по мокапу.
