### ISSUE TITLE
Реализация вывода контента на сайте-визитке ресторана (8 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#44]
### Конечный результат:
Требуется реализовать вывод контента ресторана на сайте-визитка, чтобы у клиента была возможность просматривать наличие блюд у ресторана.

### План решения:
В рамках данной задачи двам необходимо реализовать вывод имеющихся меню, кагорий, блюд и акций, который вносит ресторатор через ресурс Старкит. Также требуется вывести в хэдере и футере (согласно мокап) контактные данные ресторана из профиля (наименование ресторана, номер телефона, описание).
Для вывода данных на сайте-визитка, принадлежащих конкретному ресторану, используйте связку артефактов ресторана с сущностью Restaurant.

### Мотивация: 
На данный момент у клиентов нет возможности просмотра меню блюд и акций на сайт-визитке.

### Критерии приемки:
Сайт-визитка ресторана должен отображать имеющиеся меню блюд и действующие акции, заведенные ресторатором на ресурсе Старкит.

### Планируемое время:
8 часов

**Comment by Samat090598** [comment]
Закончил за 6 часов. Дизайном страницы не занимался. Потрачено много времени потому что, пришлось переделывать почти все контроллеры(добавить при созданий Id ресторана, при отображений списка получить по Id ресторана, сделать валидацию при проверки названий опять же по Id ресторана, и изменить расположение картинки для всех моделей которые хранят путь к картинке).
