### ISSUE TITLE
Роль отображается на английском языке 

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#45]
### Шаги воспроизведения:
Захожу под ролью Регистранта на страницу Список сотрудников и просматриваю список имеющихся записей.

### Наблюдаемое поведение: 
Запись с ролью Администратор заведения в спике отображает название роли на английском языке. См скрин
![photo_2020-08-27_23-16-55](https://user-images.githubusercontent.com/18418768/91477015-96864180-e8bf-11ea-86df-d46aaf1db896.jpg)

### Ожидаемое поведение:
Пользователь должен видеть все надписи на русском языке.

### Причины: 
Очевидно не подставляется в поле название роли на русском языке

### Вариант решения: 
Нужно вывести роль на русском языке

**Comment by seyderaly98** [comment]
Затраченное время 40 минут.
