### ISSUE TITLE
Не отображаются наименивания акций на сайте-визитка

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#46]
### Шаги воспроизведения:
Захожу на главную страницу сайта-визитки

### Наблюдаемое поведение: 
Раздел акций отображает их картинки, но наименовании акций нет. Никакого текста по акциям не отображается.
![photo_2020-08-27_21-53-02](https://user-images.githubusercontent.com/18418768/91477462-33e17580-e8c0-11ea-8e60-f69c5e884e06.jpg)

### Ожидаемое поведение:
Пользователь должен видеть названия акций, которые занесены Администратором
![photo_2020-08-27_21-53-10](https://user-images.githubusercontent.com/18418768/91477580-5d020600-e8c0-11ea-9d91-ad7719407b10.jpg)

### Причины: 
Не доработан вывод названия акция на странице

### Вариант решения: 
Нужно добавить вывод названия акция на странице

**Comment by Samat090598** [comment]
Добавил наименования акций на сайт визитку. Потраченное время 10 минут
