### ISSUE TITLE
Реализация бронирования столиков через сайт-визитку (16 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#48]
### Конечный результат:
Требуется реализовать бронирование столиков через сайт-визитку.

### План решения:
Задачи:
•	Предоставить клиенту информацию о доступных столиках в заведении с отображением столика и кол-ва посадочных мест
•	Добавить функционал по бронированию выбранного столика на определенное время и дату
Реализация:
На сайте-визитка реализовать карточки столиков с выводом следующей информации:
•	Статус столика (Свободен или Занят)
•	Если столика в статусе Занят, то необходимо отображать время действия брони
•	Номер стола
•	Количество мест
•	Изображение/я стола
•	Краткое описание расположения стола в помещении
При открытии (клике) карточки стола должно открываться модальное окно для бронирования со следующими полями ввода:
•	Дата и время бронирования 
•	Имя ФИО клиента
•	Телефон клиента
•	Кол-во гостей
•	Действие (Кнопка) Забронировать
Для забронированных пользователем столов необходимо реализовать счетчик. При клике на счетчике должен осуществляться переход к списку карточек забронированных столиков. Открытие карточки должно давать возможность пользователю снять бронь путем нажатия кнопки «Отменить бронь».
Процесс:
![image](https://user-images.githubusercontent.com/18418768/91665273-3210ef80-eb16-11ea-9cd1-d9a8e3c3923c.png)
 
Рисунок 14
Описание экранов:
![image](https://user-images.githubusercontent.com/18418768/91665277-3ccb8480-eb16-11ea-9426-b35e5d0dd610.png)
 
Рисунок 15
![image](https://user-images.githubusercontent.com/18418768/91665282-4359fc00-eb16-11ea-87c2-8a597a32d05a.png)
 
Рисунок 16

### Мотивация: 
На данный момент у клиентов нет возможности просматривать доступные столики заведения и бронировать их на сайт-визитке.

### Критерии приемки:
Пользователь заходит на сайт-визитку заведения. В меню сайта открывает раздел Бронирование столиков. В разделе открывается список карточек столов с краткой информацией.  Пользователь открывает одну из карт и заполняет поля модального окна и нажимает кнопку Забронировать.
Список карточек столов отображает по 10 карточек, пользователь нажимает на стрелки вперед/назад либо на номер страницы и переходит на нужную страницу со списком карточек. 
Забронированные пользователем стол/ы должны отображаться счетчиком в верхней панели меню, при переходе на который открывается список забронированных столиков в виде карточек. При открытии карточки забронированного столика пользователь может нажать кнопку «Отменить бронь».
Ниже размещается панель, где пользователь вводит условия бронирования мест ресторана.

### Планируемое время:
16 часов

**Comment by samzhex** [comment]
Затрачено 18 часов
