### ISSUE TITLE
Реализация управления бронированием столиков (16 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#49]
### Конечный результат:
Требуется предоставить Администратору заведения возможность управлять бронированием столиков в заведении и управлять карточками столиков.

### План решения:
Задачи:
•	Дать Администратору заведения просматривать наличие свободных и освобождающихся столиков, чтобы понимать наличие существующих броней.
•	Дать возможность создавать, редактировать и удалять карточки столиков заведения
Реализация:
Ввести сущность «Карточка столика» со следующими параметрами:
•	ID карточки
•	Дата время создания карточки
•	Статус состояния стола (Свободен или Забронирован)
•	Желаемые дата и время брони стола
•	Номер стола
•	Количество мест
•	Комментарии (описание расположения стола в зале)
•	Файлы для изображения стола
•	Имя (ФИО клиента)
•	Телефон клиента
Для удобства управления информацией о столе необходимо реализовать карточку с выводом следующих полей:
•	Статус состояния стола (Свободен или Забронирован)
•	Желаемые дата и время брони стола
•	Номер стола
•	Количество мест
•	Комментарии (описание расположения стола в зале)
•	Файлы для изображения стола. При выборе изображения стола, система будет предлагать изображения с видами столов и посадочных мест. Также есть возможность добавить фото с изображением стола.
•	Действия (Кнопки Редактировать и Удалить)
Список карточек столиков необходимо вывести в раздел Бронирование с указанием информации о бронировании возможностью редактирования. 
Также Администратору доступна кнопка «Создать столик», при нажатии на которой появляется форма для внесения информации о столике заведения. На форме должна быть кнопка Сохранить. При добавлении столика система должна предлагать варианты схем столиков с кол-вом посадочных мест, либо фотографии столиков с изображением интерьера заведения.
Описание экранов:
![image](https://user-images.githubusercontent.com/18418768/91665373-f0cd0f80-eb16-11ea-9767-f5cb26bf35f2.png)
Рисунок 17
![image](https://user-images.githubusercontent.com/18418768/91665382-f9254a80-eb16-11ea-990a-aba593769598.png)
Рисунок 18

### Мотивация: 
На данный момент у Администратора заведения нет возможности управлять бронированием столиков в заведении и управлять карточками столиков.

### Критерии приемки:
Сайт-визитка ресторана должен отображать имеющиеся меню блюд и действующие акции, заведенные ресторатором на ресурсе Старкит.

### Планируемое время:
16 часов

**Comment by samzhex** [comment]
Затраченное время 15 часов
