### ISSUE TITLE
Реализация формирования заказов на сайте-визитка (16 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#50]
### Конечный результат:
Требуется реализовать функционал на сайте-визитка по формированию заказов блюд клиентами.

### План решения:
Задачи:
•	Предоставить клиенту через сайт-визитку информацию о наличии блюд заведения и возможность заказа блюд с доставкой к определенному времени и дате.
Реализация:
На сайте-визитка: 
Добавить в карточку блюда кнопку Заказать. При нажатии это кнопки блюдо должно перемещаться в корзину.
В верхнее меню добавить кнопку с изображением Корзина. При наличии в Корзине заказов рядом с изображением Корзина должна отображаться сумма заказов.
При переходе в Корзину должна отображаться форма со списком сделанных пользователем заказов. На форме должна быть кнопка «Оформить заказ», по нажатию которой формируется заказ, присваивается ему номер и сформированный заказ отправляется к администратору заведения. На форме Корзина должны быть доступны Условия оплаты и доставки.
В Корзине пользователь может удалить заказ или изменить кол-во блюд.  При этих действиях сумма всего заказа должна пересчитываться.
Процесс:
 
![image](https://user-images.githubusercontent.com/18418768/91665506-ea8b6300-eb17-11ea-907d-261b29af5f69.png)

Рисунок 19
Описание экранов:
![image](https://user-images.githubusercontent.com/18418768/91665515-f2e39e00-eb17-11ea-8001-16d9ecbeb9c0.png)
 
Рисунок 20
 
![image](https://user-images.githubusercontent.com/18418768/91665517-fbd46f80-eb17-11ea-85d2-1028eedb0845.png)

Рисунок 21

### Мотивация: 
На данный момент у клиентов нет возможности производить заказы блюд на сайт-визитке.

### Критерии приемки:
Клиент видит список блюд с краткой информацией в виде карточек, при необходимости нажимает на карту чтобы посмотреть детали. На карте пользователь нажимает кнопку Заказать. Заказанный товар отображается в Корзина. Пользователь переходит в Корзина. В Корзине пользователь нажимает кнопку Оформить заказ. Сформированный заказ отображается у Администратора заведений..

### Планируемое время:
16 часов

**Comment by Samat090598** [comment]
Закончил за 13 часов. Много времени было потрачено на поиск решения, так как прежде не сталкивался с такой задачей, и не использовал сессий. И еще нужно было дорабатывать это решения под логику своего приложения.

**Comment by Samat090598** [comment]
Общее потраченное время 15 часов
