### ISSUE TITLE
Реализация управления списком заказов (16 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#51]
### Конечный результат:
Требуется реализовать возможность для Администратора заведения управлять списком заказов с возможностью их редактирования.

### План решения:
Реализация:
Ввести сущность Заказ со следующими параметрами:
•	Дата время
•	Номер заказа
•	Статус
•	Список блюд
•	Сумма
•	Имя (ФИО клиента)
•	Телефон
•	Адрес
•	Способ доставки
•	Комментарии к заказу
•	Действие (Кнопки Редактировать, Принять, Удалить)
Описание экранов:
![image](https://user-images.githubusercontent.com/18418768/91665615-b4021800-eb18-11ea-83bc-a04c2ce37570.png)
 
Рисунок 22

### Мотивация: 
На данный момент у Администратора нет возможность получать заказы и управлять ими.

### Критерии приемки:
Пользователь видит список заказов с краткой информацией в виде таблицы, при необходимости нажимает на Редактировать/Принять/Удалить. Над таблицей доступны функции поиска, сортировки и фильтра. Список отображает по 10 заказов, пользователь нажимает на стрелки вперед/назад либо на номер страницы и переходит на нужную страницу со списком заказов. При клике на строку заказа переход на страницу заказа с развернутой информацией.

### Планируемое время:
16 часов

**Comment by Samat090598** [comment]
Закончил за 8 часов.
