### ISSUE TITLE
Реализация Google Maps (8 часов)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#52]
### Конечный результат:
Требуется реализовать возможность клиентам просматривать наглядную информацию о месторасположении ресторана.

### План решения:
Задачи функционала:
•	На сайте-визитка в разделе Контакты/Как к нас найти разместить карту Google Maps с указанием географического расположения заведения.
Реализация:
Для использования API-карт Google http://code.google.com/intl/ru/apis/maps/ получить специальный ключ. Для получения ключа к API Карт требуется аккаунт Google, поскольку ваш ключ API будет связан с вашим аккаунтом. Получить собственный аккаунт можно по адресу https://www.google.com/accounts/ManageAccount
На данной странице выбрать ссылку Создайте аккаунт прямо сейчас. И пройти процедуру регистрации. После этого войти в Ваш аккаунт введя полученные при регистрации логин и пароль (с этого шага начинают все те, кто уже зарегистрирован на Google).
Необходимо перейти по адресу http://code.google.com/intl/ru/apis/maps/signup.html для получения ключа к API-карт Google.
На данной странице необходимо прочитать и согласиться с условиями и положениями службы и ввести url-адрес Вашего сайта.
Лучше всего в качестве адреса сайта указывать только его домен (например, mysayt.ru).
Тогда ключ, зарегистрированный на отдельный домен, будет действителен для всех url внутри этого домена и для специальных поддоменов (например для «www»).
Для работы на локальном компьютере с именем localhost, Вым необходимо зарегистрировать ключ для сайта с адресом http://localhost.
После нажатия на кнопку Сгенерировать ключ к API будет выполнена автоматическая генерация ключа и сформированы примеры использования данного ключа.
Например, ключ :
BQIAAAACHCJdlgAEGcD_flKUFEmVhT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTeukKcKHF3ezmjTB0q6gzSBmoIUQ
Код JavaScript Maps API Example:
...
  // Note: you will need to replace the sensor parameter below with either an explicit true or false value.
  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=true_or_false&amp;key=BQIAAAACHCJdlgAEGcD_flKUFEmVhT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTeukKcKHF3ezmjTB0q6gzSBmoIUQ" type="text/javascript"></script>
...
Код Maps API for Flash Example:
...
  <maps:Map xmlns:maps="com.google.maps.*" id="map" mapevent_mapready="onMapReady(event)" width="100%" height="100%"
    key="BQIAAAACHCJdlgAEGcD_flKUFEmVhT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTeukKcKHF3ezmjTB0q6gzSBmoIUQ"/>
...
Код HTTP Service Example:

http://maps.google.com/maps/geo?q=1600+Amphitheatre+Parkway,+Mountain+View,+CA&output=json&oe=utf8
&sensor=true_or_false&key=BQIAAAACHCJdlgAEGcD_flKUFEmVhT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTeukKcKHF3ezmjTB0q6gzSBmoIUQ
Приведу простейший код для использования API-карт Google:
<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Пример API Карт Google на языке JavaScript</title>
    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAACHCJdlgAEGcD_flKUFEmVhT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTeukKcKHF3ezmjTB0q6gzSBmoIUQ&sensor=true_or_false"
            type="text/javascript"></script>
    <script type="text/javascript">
 
    function initialize() {
      if (GBrowserIsCompatible()) {
        var map = new GMap2(document.getElementById("map_canvas"));
        map.setCenter(new GLatLng(56.32811,44.0), 10);
      }
    }
    </script>
  </head>
  <body onload="initialize()" onunload="GUnload()">
    <div id="map_canvas" style="width: 500px; height: 300px"></div>
  </body>
</html>
Центр карты задается командой map.setCenter(new GLatLng(56.32811,44.0), 10); , где 10 — означает уровень масштаба.
Описание экрана: 
![image](https://user-images.githubusercontent.com/18418768/91665675-2ffc6000-eb19-11ea-8cc6-efee0c5eb529.png)
Рисунок 27
![image](https://user-images.githubusercontent.com/18418768/91665687-430f3000-eb19-11ea-97e1-7e8302562855.png)
Рисунок 28

### Мотивация: 
На данный момент у клиентов нет возможности просмотра месторасположения заведения на сайт-визитке.

### Критерии приемки:
Клиент заходит на сайт-визитку и в разделе Контакты /Как нас найти видит карту с расположением заведения.

### Планируемое время:
8 часов

**Comment by samzhex** [comment]
Затрачено 2,5 часа
