### ISSUE TITLE
Добавить в акцию поле Стоимость (2 часа)

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#56]
### Конечный результат:
У Администратоа заведения должна быть возможность указывать Стоимость акции.

### План решения:
Поле Стоимость  добавить на форму акции

### Критерии приёмки:
При заполнении акции Администратор заполняет стоимость. Также стоимость должна отображаться на сайте-визитка и при выборе заказа отображается в Корзине.

### Планируемое время:
2 часа

**Comment by Samat090598** [comment]
Закончил за 1,5 часа. Проблем не возникло
