### ISSUE TITLE
Исправление формата пути картинки (2 часа)

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#61]
**Конечный результат:**
На нашем сервере все картинки должны отображаться корректно. 

**План решения:**
Изменить все пути в исходном коде например с "wwwroot\\images\\" на правый слэш "wwwroot/images/"

**Мотивация:**
На данный момент в нашем сервере не отображаются картинки. 

**Критерии приемки:**
На сайте все картинки должны отображаться корректно.

**Планируемое время:**
2 часа

**Comment by samzhex** [comment]
Затраченное время 15 минут
