### ISSUE TITLE
Реализация вывода статистики продаж (10 часов)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#66]
**Конечный результат:** 
Добавить пользователю возможность просматривать статистику продаж ресторана

**План решения:** 
Выводить данные: 
По заказам:
•	За день, 
•	За неделю, 
•	За месяц, 
•	За 3 месяца
•	За год, 
•	За все время
•	За период
•	Популярные блюда
•	Популярное меню
•	Популярные акции
•	Время

![Статистика](https://user-images.githubusercontent.com/44899374/93574514-5136ca80-f9ba-11ea-99ac-a83080eb0f90.png)

Можно воспользоваться https://code.google.com/archive/p/googlechartsharp/

**Мотивация:** 
Статистика необходима для анализа продаж ресторана и планирования дальнейшей стратегии маркетинга

**Критерии приёмки:**
Пользователь переходит во вкладку «Статистика», выбирает какие данные и за какой период необходим вывести. Видит результат. При клике на блюдо переходит на страницу выбранного блюда.

**Планируемое время работы:**
10 часов

**Comment by Samat090598** [comment]
Закончил за 10 часов. Проблема возникало с получением данных по популярным продуктам из базы данных и показа статистики по дням, неделям и т.д
