### ISSUE TITLE
Фильтрация, пагинация, поиск, сортировка блюд с помощью ajax

### ISSUE THREAD

**Issue by Samat090598** [ESDP-Csharp-2-3-Team1/starkit#7]
Конечный результат: 
У пользователя должна быть возможность управлять списком блюд и производить поиск.

План решения: 
На странице со списокм блюд необходимо реализовать панель управления фильтрацией и поиском блюд. На той же странице также требуется реализовать пагинацию, чтобы большой список можно было листать постранично. Кол-во блюд на одной странице нужно подобрать под размер экрана чтобы список помещался в размер экрана без прокрутки скролла вверх-вниз. В заголовке таблицы отображающей список добавить возможность сортировки по наименованию, дате добавления, по стоимости, по категории или калорийности.

Мотивация:

Критерии приёмки:
Открываем страницу со списком и пробуем сделать сортировку. В сортированнам списке делаем фильтрацию блюд по категории или диапозану цен. Производим поиск по названию или диапозону дат добавления.

Планируемое время работы:
1 день

**Comment by Samat090598** [comment]
Закончил за 9,5 часа. Единственное, при фильтраций и в поиске не осуществляется прежние параметры сортировки. Я думаю это будет как-то странно. Но при сортировки сохраняется прежние параметры фильтраций и поиска

**Comment by samzhex** [comment]
Сейчас при поиске нужно учитывать регистр в строке поиска, это неудобно поэтому в коде надо привести строку поиска  и наименование блюда к верхнему или нижнему регистру. Label фильтра заменить на "Категорию"

**Comment by Samat090598** [comment]
Исправил регистрозависимость и label категорий. Спасибо за быструю обратную связь.
