### ISSUE TITLE
Реализовать автоматизацию сборки и доставки приложения при помощи Jenkins CI (5 часов)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#70]
**Конечный результат:** 
Автоматизированная сборка и поставка приложения на сервер

**План решения:** 

- Добавить репо Jenkins и обновить репозиторий Ubuntu:

> wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
> echo "deb http://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
> apt-get update

- Установить Java:

> apt install -y openjdk-8-jdk
> apt install git

- Установить Jenkins

> apt-get install -y jenkins

- Ввести код созданный при установке, скопировать в файле

> cat /var/lib/jenkins/secrets/initialAdminPassword

- Сконфигурировать проект

- Настроить сервер
Для включения данного приложения выполнить команду : sudo ufw enable 
Проверить текущие открытые порты командой : sudo ufw status verbose
sudo ufw allow 22 - разрешает входящие и исходящие подключения на 22 порту (SSH)
sudo ufw allow 80/tcp -- добавляет разрешение исходящих и входящих соединений http
sudo ufw allow 443/tcp -- добавляет разрешение исходящих и входящих соединений https
sudo ufw allow 8080/tcp -- добавляет разрешение исходящих и входящих соединений на порту 8080 (Интерфейс Jenkins)
Добавить новый профиль  Jenkins в файл launchSettings.json
"Jenkins": {
     "commandName": "Project",
     "launchBrowser": true,
     "applicationUrl": "https://IP-address:5001;http://IP-address:5000",
     "environmentVariables": {
       "ASPNETCORE_ENVIRONMENT": "Development"
     }
   }

**Мотивация:** 
Для ускорение поставки

**Критерии приёмки:**
Приложение обновляется на сервере после изменений в Git репозитории

**Планируемое время работы:**
5 часов

**Comment by Samat090598** [comment]
Закончил примерно за 32 часа. Раньше не сталкивался с этой технологией Просмотрел #8, #9 занятия ESDP по Jenkins-у. И узнал что можно настроить CI/CD без Jenkins-а, с помощью Github Actions. Большое количество времени было потрачено на изучение материала и эксперименты. В ходе настройки CI/CD практический в каждом шагу возникали какие-то ошибки(проблемы).
