### ISSUE TITLE
Сверстать блок с выводом Блюд по категориям на сайте визитке (5 часов)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#79]
**Конечный результат:** 
Блок блюд с выводом по категориям:
<img width="1044" alt="Screen Shot 2020-09-23 at 20 52 30" src="https://user-images.githubusercontent.com/44899374/94030045-32cc3700-fddf-11ea-83d0-7fd0c2038a30.png">

**План решения:** 
Сверстать блок по предложенному образцу  https://radiustheme.com/demo/wordpress/redchili/food-menu-with-isotope/,  вместо меню выводить блюда, добавить анимацию и фильтрацию при помощи ajax. Так как этот фон используется в блоке акции, заменить изображения для фона, можно подобрать на https://unsplash.com/ или https://www.freepik.com/

В карточках блюд сохранить возможность выбирать количество и добавлять в корзину как в текущей верстке:
<img width="436" alt="Screen Shot 2020-09-23 at 20 58 54" src="https://user-images.githubusercontent.com/44899374/94030473-ab32f800-fddf-11ea-81c8-6b65221f0fe3.png">

**Мотивация:** 
Красивый, удобный и понятный интерфейс поможет увеличить конверсию на сайте.

**Критерии приёмки:**
Клиент переходит в блок Блюд, при клике на Категории загружаются блюда выбранной категории. Верстка должна быть адаптивной и корректно отображаться на всех устройствах. Также проходить проверку на http://validator.w3.org/

**Планируемое время работы:**
5 часов

**Comment by Samat090598** [comment]
Потратил 4 часа на задачу. Больше времени потратил на понимание кода, что где стоит
