### ISSUE TITLE
Реализовать личный кабинет

### ISSUE THREAD

**Issue by 7119967** [ESDP-Csharp-2-3-Team1/starkit#8]
Конечный результат:
У пользователя должна быть возможность увидеть свои данные и изменить пароль
 
План решения:
В рамках данной задачи чтобы реализовать редактирование пароля используем ajax.  

Критерии приёмки:
Пользователь нажимает на ссылку личного кабинета, и может увидеть там свои данные, еще там должна находится кнопка для изменения пароля. По нажатию на эту кнопку появляется модальное окно с формой для заполнение старого и нового пароля. При неправильном заполнений старого пароля должна сработать валидация.

Планируемое время работы:
1 день

**Comment by samzhex** [comment]
Затраченное время 7 часов.
