### ISSUE TITLE
Доработать блок меню (6 часов)

### ISSUE THREAD

**Issue by samzhex** [ESDP-Csharp-2-3-Team1/starkit#88]
**Конечный результат:** 
Блок меню должен соответствовать дизайну с полной информацией о меню в модальном окне и рабочим функционалом.

**План решения:** 
<img width="1297" alt="Screen Shot 2020-10-07 at 18 38 54" src="https://user-images.githubusercontent.com/44899374/95332064-b6e8e900-08cc-11eb-9a73-0fede2cbe4dc.png">

**Мотивация:** 
Красивый, удобный и понятный интерфейс поможет увеличить конверсию на сайте.

**Критерии приёмки:**
Должны работать ссылки и весь функционал. 

**Планируемое время работы:**
6 часов

**Comment by Samat090598** [comment]
Потратил час. Не смог понять какой css был использован. Оставил ссылки на css которые были на SiteCards/Index. Верстка испортился
