### ISSUE TITLE
Разработать функционал ввод капчи "CAPTCHA" 

### ISSUE THREAD

**Issue by seyderaly98** [ESDP-Csharp-2-3-Team1/starkit#9]
**Конечный результат:**
После заполнения обязательных полей формы регистрации необходимо заполнить капчу. Кнопка регистрации не должно срабатывать если капча неправильно веден. 

**План решения:**
В рамках данной задачи, от вас потребуется реализовать следующий функционал:
●	К форму регистрации добавить функционал ввода капчи 
○	

**Критерии приема:**
Есть несколько вариантов, таких как Google ReCaptcha и Google ReCaptcha. captcha.com оба они могут быть интегрированы в ASP.NET. Также можно  сгенерировать код captcha самостоятельно, этот пост покажет вам, как генерировать и использовать код captcha https://edi.wang/post/2018/10/13/generate-captcha-code-aspnet-core.

**Планируемое время:**
1 день

**Comment by samzhex** [comment]
Затраченное время 4 часа
